---
# Kubernetes version
#rancher_kubernetes_version: "v1.22.13-rancher1-1"
# 
# Rancher RKE cluster URL
#kubernetes_cluster_url: "https://rancher.example.com/v3/clusters/c-vh2ns"
# 
# Rancher RKE cluster name
#cluster_name: "example-prod"

#Rancher API credencials
#rancher_api_username: "token-bj8nm"
#rancher_api_password: "kjf6vasdf1234asdf1234asdf1234asdf1234asdf1234asdf17fpx"

# Define path to kubectl and kubeconfig
kubectl_downstream: "{{ path_to_kubectl }} --kubeconfig={{ kubeconfig_downstream }}"
kubectl_local: "{{ path_to_kubectl }} --kubeconfig={{ kubeconfig_local }}"

# Define drain command with options
kubectl_drain_command: "{{ kubectl_downstream }} drain --ignore-daemonsets --force --grace-period=150 --timeout=300s --delete-emptydir-data"

# Docker version
#docker_version: 20.10.12*

# Pause seconds between worker nodes for example to allow cloud native storage to rebalance
# Default is 5, overwrite it with -e
pause_seconds_between_workers: 30