---
- name: "Sleep for {{ pause_seconds_between_workers }} seconds, e.g. for storage rebuilding"
  wait_for:
    timeout: "{{ pause_seconds_between_workers }}"
  delegate_to: localhost
  when: ansible_uptime_seconds < 600