---
- name: "Sleep for 60 seconds to allow kube daemons to restart"
  wait_for:
    timeout: 60
  delegate_to: localhost
  when: ansible_uptime_seconds < 120

- name: "Uncordon worker node"
  local_action: "command {{ kubectl_full_path }} uncordon {{ inventory_hostname }}"

- name: "Sleep for 5 minutes to allow Longhorn rebuilding"
  wait_for:
    timeout: 300
  delegate_to: localhost
  
- name: "Remove old and unused docker images"
  command: docker image prune -af
