---
- name: "Reboot"
  reboot:
  
- name: Collect Ansible facts after reboot
  setup:

- name: Remove pachages that are not needed any more
  apt:
    autoremove: yes
  ignore_errors: yes
  when: ansible_facts['os_family'] == "Debian"
