---
- name: Update RKE worker nodes
  hosts: worker_nodes
  become: yes
  become_method: sudo
  serial: 1
  tags: worker
  roles:
    - drain-node
    - update-node
    - reboot-node
    - uncordon-node
    - pause_between_workers

- name: Update RKE controlplane nodes
  hosts: controlplane_nodes
  become: yes
  become_method: sudo
  serial: 1
  tags: controlplane
  roles:
    - check-etcd-health
    - check-controlplane-health
    - update-node
    - reboot-node
    - check-etcd-health
    - check-controlplane-health

- name: Update RKE kubernetes version
  hosts: localhost
  tags: kubernetes
  tasks:
    - include_role:
        name: update-kubernetes-version